### PR TITLE
Added Travis file

### PR DESCRIPTION
**Pull request by robisrob**

### CODE REVIEW

**Comment by bartw** [comment]
The travis file builds to dotnet 1.0.1, on my machine I'm at 1.0.4.
Your fluentassertions commits are also included.

**Comment by bartw** [comment]
I just stole the .travis.yml from the pull request and committed it myself.
Sorry.

**Comment by robisrob** [comment]
That's ok. I didn't want to include the fluentassertions in the pull
request. Must have done something wrong...

**Comment by bartw** [comment]
I think that if a pull request is open all following commits get added automatically.

**Pull request closed without merging**
